name: Docker Build and Push GHCR

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ghcr.io/${{ github.repository_owner }}/drilling-activity-api:$IMAGE_TAG .
          docker tag ghcr.io/${{ github.repository_owner }}/drilling-activity-api:$IMAGE_TAG ghcr.io/${{ github.repository_owner }}/drilling-activity-api:latest

      - name: Push Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/drilling-activity-api:$IMAGE_TAG
          docker push ghcr.io/${{ github.repository_owner }}/drilling-activity-api:latest